### PR TITLE
PhantomJS2

### PR DESCRIPTION
**Pull request by nilnullzip**
Replace Phantom 1.9.12 with PhantomJS2 2.0.2.

### CODE REVIEW

**Comment by ghost** [comment]
Just found out that there is no download for Linux. So it will fail to install on Linux. https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by nilnullzip** [comment]
Hmm. I wonder if that phantomjs2 node install is perhaps not the preferred way to install 2.0? I'm poking around trying to figure it out.

**Comment by ghost** [comment]
It seems they are very close to provide builds for the Linux distributions: https://github.com/ariya/phantomjs/issues/13822. I will release a new version that has the PHANTOMJS_BIN environment variable option in, that was in your first pull request. When they are providing builds for Linux with PhantomJS 2.1, we can make it the default and also do a pull request upstream to meteor/meteor.

**Comment by nilnullzip** [comment]
Cool. Thanks! -Juan

**Comment by ghost** [comment]
Still no Mac build machine available. I guess, I need to wait until they are back from holidays and start their Mac build machine :D

**Pull request merged**
